### PR TITLE
chore: Remove ALB

### PR DESCRIPTION
**Pull request by karimatwa**
This pull request:
- Removes the usage of ALB from the private package solution since it's not required. End users can directly use the task's public IP with the port number. Additionally, it's not recommended to create networking components from our solution's Terraform. A client expressed concern about the use of ALB.
- Removes the optional field conf_s3_object_name as we only need to mention mandatory fields.
- Updates the instance type to the new AWS compute-optimized family c7i.xlarge.

### CODE REVIEW

**Comment by slandelle** [comment]
How would customers configure HTTPS when using Private Packages?

**Comment by karimatwa** [comment]
They can do this by creating a domain and certificate, and then creating a DNS record on Route 53 on their own. Alternatively, they can set up an ALB listening on port 443 and use the ALB endpoint directly or alias it with Route 53.

These are optional steps that we should not include in these Terraform configs. Moreover, we should not create network components that might make clients wary, such as VPCs, security groups, routers, or ALBs.

**Comment by karimatwa** [comment]
> How would customers configure HTTPS when using Private Packages?

They can do this by creating a domain and certificate, and then creating a DNS record on Route 53 on their own. Alternatively, they can set up an ALB listening on port 443 and use the ALB endpoint directly or alias it with Route 53.

These are optional steps that we should not include in these Terraform configs. Moreover, we should not create network components that might make clients wary, such as VPCs, security groups, routers, or ALBs.

**Comment by slandelle** [comment]
Good for me, but I think we should mention these missing points in the documentation.

**Review by slandelle — APPROVED** [review]

**Pull request merged**
